name: Build with Maven directly

on:
  push:
    paths-ignore:
      - '*.md'
      - 'images/**'
  pull_request:
    paths-ignore:
      - '*.md'
      - 'images/**'
  workflow_dispatch:

jobs:
  build:
    name: Builds and tests
    runs-on: ubuntu-latest
    # First run in GitHub actions - verify this
    # Afterwards, change to a comment
    strategy:
      matrix:
        include:
          - java: 21

    steps:
      - name: Clone repository
        uses: actions/checkout@master

      - name: Restore Maven caches
        uses: actions/cache@master
        env:
          cache-name: maven-cache
        with:
          path: ~/.m2
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Build and test
        run: ./mvnw clean verify

      - name: Execute run script
        run: ./run-with-maven.sh
