name: Build with Gradle using Earthly

on:
  push:
    paths-ignore:
      - '*.md'
      - 'images/**'
  pull_request:
    paths-ignore:
      - '*.md'
      - 'images/**'
  workflow_dispatch:

jobs:
  build:
    name: Builds and tests
    runs-on: ubuntu-latest
    # First run in GitHub actions - verify this
    # Afterwards, change to a comment
    strategy:
      matrix:
        include:
          - java: 21

    steps:
      - name: Use Earthly
        uses: earthly/actions-setup@v1
        with:
          version: "latest"

      - name: Clone repository
        uses: actions/checkout@master

      - name: Restore Gradle caches
        uses: actions/cache@master
        env:
          cache-name: gradle-cache
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{hashFiles('**/build.gradle') }}
          # TODO: See discussion: https://github.com/jeremylong/DependencyCheck/issues/2560#issuecomment-702098748
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Build and test
        run: earthly +build-with-gradle

      - name: Execute run script
        run: earthly +run-with-gradle
